name: Issue Auto Comment

on:
  issues:
    types:
      - opened
      - closed
      - assigned
  pull_request_target:
    types:
      - opened
      - closed

permissions: 
  contents: read

jobs:
  run:
    permissions: 
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Auto comment for Issues opened
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          issuesOpened: |
            ğŸ‰ **@{{ author }}**

            <details>
              <summary>ğŸš€ Thanks for opening this issue! ğŸš€</summary>
              If you have any more questions, feel free to ask. ğŸ¤—
              We are happy to help you! ğŸ‰
            </details>

      - name: Auto comment for Issues closed
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          issuesClosed: |
            ğŸ‰ **@{{ author }}**

            <details>
              <summary>ğŸš€ Thanks for closing this issue! ğŸš€</summary>
              If you have any more questions, feel free to ask. ğŸ¤—
              We are happy to help you! ğŸ‰
            </details>

      - name: Auto comment for Pull Requests opened
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          pullRequestOpened: |
            ğŸ‰ **@{{ author }}**

            <details>
              <summary>ğŸš€ Thanks for opening this pull request! ğŸš€</summary>
              If you have any more questions, feel free to ask. ğŸ¤—
              We are happy to help you! ğŸ‰
            </details>

      - name: Auto comment for Pull Requests merged
        uses: actions-cool/pr-welcome@main
        if: github.event.pull_request.merged == true
        with:
          token: ${{ secrets.GH_TOKEN }}
          comment: |
            ğŸ™ **@${{ github.event.pull_request.user.login }}** ğŸ™
            
            **Congratulations on merging this pull request!** ğŸš€
            Thanks for your contribution to our Community! ğŸ‰
            If you have any more questions, feel free to ask. ğŸ¤—
            We are happy to help you! ğŸ‰
        
      - name: Remote inactive
        if: github.event.issue.state == 'open' && github.actor == github.event.issue.user.login
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'Inactive'